// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrainCoach.Infrastructure.Persistence;

#nullable disable

namespace TrainCoach.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TrainCoachDbContext))]
    [Migration("20260915101035_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TrainCoach.Domain.Execution.ActivityMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompletedActivityId")
                        .HasColumnType("uuid");

                    b.Property<int>("MetricType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Value")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.HasKey("Id");

                    b.HasIndex("CompletedActivityId", "MetricType", "Source");

                    b.ToTable("ActivityMetrics");
                });

            modelBuilder.Entity("TrainCoach.Domain.Execution.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthorRole")
                        .HasColumnType("integer");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlannedWorkoutId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlannedWorkoutId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("TrainCoach.Domain.Execution.CompletedActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("AverageHeartRateBpm")
                        .HasColumnType("integer");

                    b.Property<int?>("AveragePaceSecondsPerKm")
                        .HasColumnType("integer");

                    b.Property<int?>("AveragePowerWatts")
                        .HasColumnType("integer");

                    b.Property<int?>("Calories")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DistanceMeters")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ElevationGainMeters")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxHeartRateBpm")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PlannedWorkoutId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sport")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlannedWorkoutId");

                    b.HasIndex("AthleteUserId", "StartedAtUtc");

                    b.ToTable("CompletedActivities");
                });

            modelBuilder.Entity("TrainCoach.Domain.Execution.DataProvenance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompletedActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ImportedFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("text");

                    b.Property<bool>("RawPayloadRetained")
                        .HasColumnType("boolean");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SynchronizationRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompletedActivityId")
                        .IsUnique();

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique()
                        .HasFilter("\"ExternalId\" IS NOT NULL");

                    b.ToTable("DataProvenances");
                });

            modelBuilder.Entity("TrainCoach.Domain.Execution.TrainingFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompletedActivityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("FreeText")
                        .HasColumnType("text");

                    b.Property<int?>("LegsFeeling")
                        .HasColumnType("integer");

                    b.Property<int?>("OverallRating")
                        .HasColumnType("integer");

                    b.Property<string>("PainNote")
                        .HasColumnType("text");

                    b.Property<Guid?>("PlannedWorkoutId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Rpe")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId", "Date");

                    b.ToTable("TrainingFeedbacks");
                });

            modelBuilder.Entity("TrainCoach.Domain.Identity.AthleteProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CurrentWeightKg")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<int?>("MaxHeartRateBpm")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PrimarySport")
                        .HasColumnType("text");

                    b.Property<int?>("RestingHeartRateBpm")
                        .HasColumnType("integer");

                    b.Property<string>("Sex")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("AthleteProfiles");
                });

            modelBuilder.Entity("TrainCoach.Domain.Identity.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TrainCoach.Domain.Identity.CoachAthleteRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoachUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InviteNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("InvitedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId", "Status");

                    b.HasIndex("CoachUserId", "AthleteUserId");

                    b.ToTable("CoachAthleteRelationships");
                });

            modelBuilder.Entity("TrainCoach.Domain.Identity.CoachProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("Certifications")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("CoachProfiles");
                });

            modelBuilder.Entity("TrainCoach.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TrainCoach.Domain.Identity.RelationshipPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RelationshipId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RelationshipId", "Scope");

                    b.ToTable("RelationshipPermissions");
                });

            modelBuilder.Entity("TrainCoach.Domain.Identity.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnboarded")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("PrimaryRole")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("TrainCoach.Domain.Integrations.ImportedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("FileType")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<DateTime?>("PreviewGeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RowsSkippedDuplicate")
                        .HasColumnType("integer");

                    b.Property<int?>("RowsTotal")
                        .HasColumnType("integer");

                    b.Property<int?>("RowsValid")
                        .HasColumnType("integer");

                    b.Property<int?>("RowsWithErrors")
                        .HasColumnType("integer");

                    b.Property<int?>("RowsWithWarnings")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId", "ContentHash");

                    b.ToTable("ImportedFiles");
                });

            modelBuilder.Entity("TrainCoach.Domain.Integrations.IntegrationConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DisconnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalAccountId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId", "Provider")
                        .IsUnique();

                    b.ToTable("IntegrationConnections");
                });

            modelBuilder.Entity("TrainCoach.Domain.Integrations.IntegrationCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AccessTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedRefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("GrantedScope")
                        .HasColumnType("text");

                    b.Property<Guid>("IntegrationConnectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationConnectionId")
                        .IsUnique();

                    b.ToTable("IntegrationCredentials");
                });

            modelBuilder.Entity("TrainCoach.Domain.Integrations.SynchronizationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IntegrationConnectionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ItemsCreated")
                        .HasColumnType("integer");

                    b.Property<int>("ItemsFetched")
                        .HasColumnType("integer");

                    b.Property<int>("ItemsSkippedDuplicate")
                        .HasColumnType("integer");

                    b.Property<int>("ItemsUpdated")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Trigger")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationConnectionId", "StartedAtUtc");

                    b.ToTable("SynchronizationRuns");
                });

            modelBuilder.Entity("TrainCoach.Domain.Nutrition.FoodEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("EstimatedCarbsGrams")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<decimal?>("EstimatedProteinGrams")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<int>("MealType")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("RelativeToWorkoutNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId", "ConsumedAtUtc");

                    b.ToTable("FoodEntries");
                });

            modelBuilder.Entity("TrainCoach.Domain.Nutrition.HydrationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CaffeineMilligrams")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<DateTime>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ContainsElectrolytes")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("DrinkType")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("VolumeMilliliters")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId", "ConsumedAtUtc");

                    b.ToTable("HydrationEntries");
                });

            modelBuilder.Entity("TrainCoach.Domain.Planning.CustomAbbreviation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("CoachUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FullText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CoachUserId", "Abbreviation")
                        .IsUnique();

                    b.ToTable("CustomAbbreviations");
                });

            modelBuilder.Entity("TrainCoach.Domain.Planning.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AchievedNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsAchieved")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("TrainCoach.Domain.Planning.HeartRateZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EffectiveFromDate")
                        .HasColumnType("date");

                    b.Property<int>("MaxBpm")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxPaceSecondsPerKm")
                        .HasColumnType("integer");

                    b.Property<int>("MinBpm")
                        .HasColumnType("integer");

                    b.Property<int?>("MinPaceSecondsPerKm")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ZoneNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId", "ZoneNumber", "EffectiveFromDate");

                    b.ToTable("HeartRateZones");
                });

            modelBuilder.Entity("TrainCoach.Domain.Planning.PlannedWorkout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoachDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CopiedFromTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CopiedFromWorkoutId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRestDay")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("PlannedDistanceMeters")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<int?>("PlannedDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PlannedElevationGainMeters")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<int>("Sport")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TrainingWeekId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("TrainingWeekId");

                    b.ToTable("PlannedWorkouts");
                });

            modelBuilder.Entity("TrainCoach.Domain.Planning.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActualResultNote")
                        .HasColumnType("text");

                    b.Property<int?>("ActualTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DistanceMeters")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<decimal?>("ElevationGainMeters")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ResultNotes")
                        .HasColumnType("text");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sport")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetResultNote")
                        .HasColumnType("text");

                    b.Property<int?>("TargetTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId", "StartsAtUtc");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("TrainCoach.Domain.Planning.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("TrainCoach.Domain.Planning.TrainingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoachUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId");

                    b.HasIndex("CoachUserId");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("TrainCoach.Domain.Planning.TrainingWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AthleteWeekReflection")
                        .HasColumnType("text");

                    b.Property<int?>("AthleteWeeklyRating")
                        .HasColumnType("integer");

                    b.Property<string>("CoachWeekSummary")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrainingPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeekIndex")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.Property<string>("WhatWasMissingNote")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId", "WeekStartDate")
                        .IsUnique();

                    b.ToTable("TrainingWeeks");
                });

            modelBuilder.Entity("TrainCoach.Domain.Planning.WorkoutSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DistanceMeters")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("IntensityTargetType")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PlannedWorkoutId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RepeatCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TargetHeartRateZoneId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TargetPaceSecondsPerKmMax")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetPaceSecondsPerKmMin")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetPowerWatts")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetRpe")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WorkoutTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlannedWorkoutId", "Order");

                    b.HasIndex("WorkoutTemplateId", "Order");

                    b.ToTable("WorkoutSegments");
                });

            modelBuilder.Entity("TrainCoach.Domain.Planning.WorkoutTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoachUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Sport")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CoachUserId");

                    b.ToTable("WorkoutTemplates");
                });

            modelBuilder.Entity("TrainCoach.Domain.Platform.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId", "ReadAtUtc");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TrainCoach.Domain.Reporting.GeneratedReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryChannel")
                        .HasColumnType("integer");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NarrativeText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId", "Date", "Type")
                        .IsUnique();

                    b.ToTable("GeneratedReports");
                });

            modelBuilder.Entity("TrainCoach.Domain.Reporting.GeneratedReportInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GeneratedReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedReportId");

                    b.ToTable("GeneratedReportInsights");
                });

            modelBuilder.Entity("TrainCoach.Domain.Wellness.DailyCheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("CompletedPlannedWorkout")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("Energy")
                        .HasColumnType("integer");

                    b.Property<int?>("Fatigue")
                        .HasColumnType("integer");

                    b.Property<bool?>("HasPainOrIllness")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("HydrationLiters")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<int?>("LegsFeeling")
                        .HasColumnType("integer");

                    b.Property<int?>("MealQuality")
                        .HasColumnType("integer");

                    b.Property<int?>("Motivation")
                        .HasColumnType("integer");

                    b.Property<int?>("MuscleSoreness")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int?>("Rpe")
                        .HasColumnType("integer");

                    b.Property<int?>("SleepQuality")
                        .HasColumnType("integer");

                    b.Property<int?>("Stress")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId", "Date", "Type")
                        .IsUnique();

                    b.ToTable("DailyCheckIns");
                });

            modelBuilder.Entity("TrainCoach.Domain.Wellness.HrvMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("MeasuredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("RmssdMs")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId", "Date", "Source")
                        .IsUnique();

                    b.ToTable("HrvMeasurements");
                });

            modelBuilder.Entity("TrainCoach.Domain.Wellness.PainOrHealthFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("BodyPart")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("RelatedCheckInId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ResolvedOnDate")
                        .HasColumnType("date");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartedOnDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId", "Status");

                    b.ToTable("PainOrHealthFlags");
                });

            modelBuilder.Entity("TrainCoach.Domain.Wellness.PerformanceBaseline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaselineValue")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MetricType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StdDeviation")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<DateOnly>("ValidFromDate")
                        .HasColumnType("date");

                    b.Property<int>("WindowDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId", "MetricType", "ValidFromDate");

                    b.ToTable("PerformanceBaselines");
                });

            modelBuilder.Entity("TrainCoach.Domain.Wellness.PersonalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AchievedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DistanceLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("RaceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sport")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId", "Sport");

                    b.ToTable("PersonalRecords");
                });

            modelBuilder.Entity("TrainCoach.Domain.Wellness.RecoveryMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("ReadinessScore")
                        .HasColumnType("integer");

                    b.Property<int?>("RestingHeartRateBpm")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int?>("StressScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId", "Date", "Source")
                        .IsUnique();

                    b.ToTable("RecoveryMetrics");
                });

            modelBuilder.Entity("TrainCoach.Domain.Wellness.SleepRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("DeepSleepMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("RemSleepMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteUserId", "Date", "Source")
                        .IsUnique();

                    b.ToTable("SleepRecords");
                });

            modelBuilder.Entity("TrainCoach.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TrainCoach.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TrainCoach.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainCoach.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TrainCoach.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainCoach.Domain.Execution.ActivityMetric", b =>
                {
                    b.HasOne("TrainCoach.Domain.Execution.CompletedActivity", "CompletedActivity")
                        .WithMany("AdditionalMetrics")
                        .HasForeignKey("CompletedActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletedActivity");
                });

            modelBuilder.Entity("TrainCoach.Domain.Execution.DataProvenance", b =>
                {
                    b.HasOne("TrainCoach.Domain.Execution.CompletedActivity", "CompletedActivity")
                        .WithOne("Provenance")
                        .HasForeignKey("TrainCoach.Domain.Execution.DataProvenance", "CompletedActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletedActivity");
                });

            modelBuilder.Entity("TrainCoach.Domain.Identity.AthleteProfile", b =>
                {
                    b.HasOne("TrainCoach.Domain.Identity.UserProfile", "UserProfile")
                        .WithOne("AthleteProfile")
                        .HasForeignKey("TrainCoach.Domain.Identity.AthleteProfile", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("TrainCoach.Domain.Identity.CoachAthleteRelationship", b =>
                {
                    b.HasOne("TrainCoach.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AthleteUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainCoach.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CoachUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainCoach.Domain.Identity.CoachProfile", b =>
                {
                    b.HasOne("TrainCoach.Domain.Identity.UserProfile", "UserProfile")
                        .WithOne("CoachProfile")
                        .HasForeignKey("TrainCoach.Domain.Identity.CoachProfile", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("TrainCoach.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("TrainCoach.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainCoach.Domain.Identity.RelationshipPermission", b =>
                {
                    b.HasOne("TrainCoach.Domain.Identity.CoachAthleteRelationship", "Relationship")
                        .WithMany("Permissions")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("TrainCoach.Domain.Identity.UserProfile", b =>
                {
                    b.HasOne("TrainCoach.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("TrainCoach.Domain.Identity.UserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainCoach.Domain.Integrations.IntegrationCredential", b =>
                {
                    b.HasOne("TrainCoach.Domain.Integrations.IntegrationConnection", "IntegrationConnection")
                        .WithOne("Credential")
                        .HasForeignKey("TrainCoach.Domain.Integrations.IntegrationCredential", "IntegrationConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegrationConnection");
                });

            modelBuilder.Entity("TrainCoach.Domain.Integrations.SynchronizationRun", b =>
                {
                    b.HasOne("TrainCoach.Domain.Integrations.IntegrationConnection", "IntegrationConnection")
                        .WithMany("SyncRuns")
                        .HasForeignKey("IntegrationConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegrationConnection");
                });

            modelBuilder.Entity("TrainCoach.Domain.Planning.PlannedWorkout", b =>
                {
                    b.HasOne("TrainCoach.Domain.Planning.TrainingWeek", "TrainingWeek")
                        .WithMany("Workouts")
                        .HasForeignKey("TrainingWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingWeek");
                });

            modelBuilder.Entity("TrainCoach.Domain.Planning.TrainingWeek", b =>
                {
                    b.HasOne("TrainCoach.Domain.Planning.TrainingPlan", "TrainingPlan")
                        .WithMany("Weeks")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("TrainCoach.Domain.Planning.WorkoutSegment", b =>
                {
                    b.HasOne("TrainCoach.Domain.Planning.PlannedWorkout", "PlannedWorkout")
                        .WithMany("Segments")
                        .HasForeignKey("PlannedWorkoutId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TrainCoach.Domain.Planning.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("Segments")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("PlannedWorkout");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("TrainCoach.Domain.Reporting.GeneratedReportInsight", b =>
                {
                    b.HasOne("TrainCoach.Domain.Reporting.GeneratedReport", "GeneratedReport")
                        .WithMany("Insights")
                        .HasForeignKey("GeneratedReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneratedReport");
                });

            modelBuilder.Entity("TrainCoach.Domain.Execution.CompletedActivity", b =>
                {
                    b.Navigation("AdditionalMetrics");

                    b.Navigation("Provenance");
                });

            modelBuilder.Entity("TrainCoach.Domain.Identity.CoachAthleteRelationship", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("TrainCoach.Domain.Identity.UserProfile", b =>
                {
                    b.Navigation("AthleteProfile");

                    b.Navigation("CoachProfile");
                });

            modelBuilder.Entity("TrainCoach.Domain.Integrations.IntegrationConnection", b =>
                {
                    b.Navigation("Credential");

                    b.Navigation("SyncRuns");
                });

            modelBuilder.Entity("TrainCoach.Domain.Planning.PlannedWorkout", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("TrainCoach.Domain.Planning.TrainingPlan", b =>
                {
                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("TrainCoach.Domain.Planning.TrainingWeek", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("TrainCoach.Domain.Planning.WorkoutTemplate", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("TrainCoach.Domain.Reporting.GeneratedReport", b =>
                {
                    b.Navigation("Insights");
                });
#pragma warning restore 612, 618
        }
    }
}
